### ISSUE TITLE
Kupfer no shadow

### ISSUE THREAD

**Issue by gianlucapettinello** [kupferlauncher/kupfer#84] opened 2017-03-25 15:16 UTC
### Environment

Kupfer Version:
Window Manager: compiz
Desktop Environment: xfce
Linux Distribution: archlinux

### Actual Behaviour
The window is small for a retina display and has no shadow

### Expected Behaviour
As the other windows it would be nice if it has a shadow below and if it can be themed. Thanks

**Comment by bluss** [comment] 2017-03-25 15:19
You can work around this using `KUPFER_WINDOW_TYPE_HINT=normal` (or maybe another type). I think some of the types will give you a shadow.

Do the icon size settings in preferences work well for you, to increase the window's size? It's why I introduced it. As usual on linux, we have a very diverse set of environments and it's hard to find a default configuration that is perfect everywhere.

**Comment by gianlucapettinello** [comment] 2017-03-25 15:23
I'll try as soon as I get back home. Thanks for the flash quick reply!

**Comment by bluss** [comment] 2017-03-25 15:26
On hidpi without any Gtk scaling, I use icon sizes 208 and 48

**Comment by gianlucapettinello** [comment] 2017-03-25 17:10
I recompiled the new version of kupfer under arch and it gives a shadow. Also your suggestion on icon size works perfectly. Thanks. 
However there are other two problems: when I type, in the past it used to show the correspondance while here it shows only one occurrence and I need to press down arrow to show the choices.
In addition in the past when I pressed enter on the text item it used to propose from locate function while now it opens firefox.
Finally (I know I'm too exigent) the corners are square but I think it is better like this
Thanks!!

**Comment by bluss** [comment] 2017-03-25 17:30
I guess you used to use the old version of Kupfer (208). That one is very old and there has been a lot of changes. Upgrading may erase some of the learned info, so if you see changes in what kupfer ranks first, it's due to that (and is corrected by itself). It's still using the same learning algo.

(Make sure to report issues for each bug, otherwise they will be forgotten.)

**Comment by bluss** [comment] 2017-03-25 18:42
The no shadow thing was apparently not a bug in current version, so closing.

**Closed by bluss** 2017-03-25 18:42 UTC

**Comment by gianlucapettinello** [comment] 2017-03-25 19:55
Thanks.
Yes problem solved

**Comment by bluss** [comment] 2017-03-25 21:49
I agree that square corners work just as well as long as the window has a shadow.
