### ISSUE TITLE
WindowController: Trying to register <Primary><Alt>space to spawn kupfer.. failed

### ISSUE THREAD

**Issue by johnjohndoe** [kupferlauncher/kupfer#135] opened 2020-10-20 19:21 UTC
### Environment
- Kupfer Version: 319
- Window Manager: Gnome 3.36.3
- Desktop Environment: ubuntu-wayland
- Linux Distribution: Ubuntu 20.04.1

### Actual Behaviour
- Kupfer can be started via the Ubuntu launcher but **not** via the keyboard shortcut.

### Expected Behaviour
- Kupfer can be started both via the Ubuntu launcher and via the keyboard shortcut.

### Debug output
``` python
...
D [kupfer.scheduler] Scheduler: Display
D [kupfer.core.data] DataController: Reloading source root
D [kupfer.scheduler] Scheduler: After Display
D [kupfer.ui.browser] WindowController: in lazy_setup

(kupfer.py:33138): Gtk-CRITICAL **: 21:06:13.061: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
Kupfer: A free software (GPLv3+) launcher
   Copyright © 2007–2017 Ulrik Sverdrup with others
   https://kupferlauncher.github.io/

[kupfer.ui.browser] WindowController: Trying to register <Primary><Alt>space to spawn kupfer.. failed
D [kupfer.ui.session] SessionClient: Connected to session as client /org/gnome/SessionManager/Client31 
D [kupfer.ui.browser] Interface: Finished lazy_setup
D [kupfer.ui.browser] WindowController: finished lazy_setup
...
```

**Comment by bluss** [comment] 2020-10-20 20:32
Duplicate of #62 

Keybinder does not support wayland. We're not alone in this, see links in the issue. Set your own global shortcuts in your window manager, it's the only way for now (applications need a unified API to access those things). Thanks

**Closed by bluss** 2020-10-20 20:32 UTC

**Comment by johnjohndoe** [comment] 2020-10-21 07:38
Thanks! I was able to configure the keyboard shortcut in *Settings* > *Keyboard Shortcuts*:

![image](https://user-images.githubusercontent.com/144518/96688238-38d31a80-1381-11eb-898e-dd6e2cca77ee.png)

**Comment by bluss** [comment] 2020-10-21 10:58
Thanks, so if Ubuntu has an API for that, we'd like to support it and support it better.

A. Add automatic setup of ubuntu keybindings? (Needs to be pluggable to support all the sessions)
B. Do we need to support a --toggle or --show-hide switch so that the keybinding can show/hide? If possible
